export const GLOBAL_KEYWORDS = [
  "CBSE Full Form",
  "ICSE Full Form",
  "DGCA Full Form",
  "PPL Full Form",
  "CPL Full Form",
  "RTR Full Form",
  "Atpl Full Form",
  "Commercial Pilot License",
  "Commercial Pilot License in India",
  "Commercial Pilot License (CPL)",
  "Pilot course",
  "Pilot Course",
  "Commercial Pilot Course",
  "Best Pilot Training Institute",
  "commercial pilot",
  "commercial pilot license salary",
  "Pilot training",
  "Pilot Training",
  "Pilot Training in India",
  "Pilot Training Institute",
  "Aviation Academy",
  "commercial pilot course",
  "commercial pilot licence course",
  "cpl course fees",
  "commercial pilot training",
  "Commercial Pilot Training",
  "commercial pilot eligibility",
  "commercial pilot training in india",
  "cpl licence cost",
  "commercial pilot license course in india",
  "commercial pilot fees",
  "commercial pilot course eligibility",
  "commercial pilot license syllabus",
  "Commercial Pilot License Admission Process",
  "Become a Pilot",
  "how to become a pilot",
  "How to Become a Pilot",
  "how to become a pilot in india",
  "how to become a pilot after 12th",
  "Private Pilot License",
  "Private Pilot License (PPL)",
  "CPL Course",
  "pilot course fees",
  "Pilot Course Fees",
  "Pilot Salary in India",
  "pilot training fees",
  "qualifications to become a pilot",
  "best pilot schools",
  "eligibility for become a pilot",
  "pilot syllabus",
  "pilot training eligibility",
  "Pilot Eligibility",
  "CPL Eligibility",
  "eligibility for pilot course",
  "ppl syllabus",
  "pilot course syllabus",
  "ppl pilot salary",
  "private pilot license syllabus",
  "Pilot training in India",
  "Pilot training in Hyderabad",
  "Pilot training in Mumbai",
  "Pilot Training in Chennai",
  "Pilot Training in Bangalore",
  "Pilot training in kerala",
  "Pilot training in Delhi",
  "Pilot Training in Pune",
  "Pilot training institute in Kolkata",
  "pilot training in coimbatore",
  "Pilot training in Gujarat",
  "Pilot training in goa",
  "Pilot Training in Gurgaon",
  "Pilot training in tamil nadu",
  "Pilot Training in Rajasthan",
  "Pilot Training in Haryana",
  "Pilot Training in Punjab",
  "Pilot Training in Andhra Pradesh",
  "Pilot Training in Arunachal Pradesh",
  "Pilot training in Assam",
  "Pilot Training in Bihar",
  "Pilot Training in Chhattisgarh",
  "Pilot Training in Himachal Pradesh",
  "Pilot Training in Noida",
  "Pilot Training in Ghaziabad",
  "Pilot Training in Nagpur",
  "Pilot Training in Maharashtra",
  "Pilot Training in Jaipur",
  "Airline Transport Pilot License",
  "airline transport pilot license",
  "atpl",
  "atpl license",
  "airline transport license",
  "atp licence",
  "airline transport pilot licence cost",
  "atpl cost",
  "atpl requirements",
  "atpl training",
  "atpl pilot salary",
  "Student Pilot License",
  "spl",
  "student pilot license",
  "student pilot certificate",
  "student pilot license cost",
  "spl pilot training fees",
  "student pilot license requirements",
  "student pilot license eligibility",
  "student pilot license fees",
  "spl eligibility",
  "spl fees",
  "Pilot Training Course",
  "DGCA",
  "DGCA Ground Class",
  "DGCA Ground Classes",
  "DGCA Ground School",
  "DGCA Coaching",
  "DGCA Computer Number",
  "DGCA Exams",
  "ground class",
  "dgca pariksha",
  "pariksha dgca",
  "dgca exam",
  "dgca central examination organization",
  "pilot exam",
  "dgca pariksha portal",
  "dgca exam fees",
  "dgca exam for pilot",
  "dgca exam eligibility",
  "dgca pilot exam",
  "what is dgca exam",
  "dgca exam date",
  "dgca cpl exam",
  "dgca exams for cpl",
  "www pariksha dgca",
  "how to apply for dgca exam",
  "dgca exam age limit",
  "dgca exam schedule",
  "dgca pariksha com",
  "aviation exam in india",
  "dgca entrance exam",
  "e pariksha dgca",
  "egca login",
  "egca",
  "egca dgca",
  "dgca login",
  "edgca",
  "ecga",
  "egca full form",
  "egca registration",
  "RTR(A)",
  "RTR(A) Classes",
  "Flying School",
  "Flying Schools",
  "Flight Training",
  "Aviation Career",
  "Airline Pilot Training",
  "Airline Career",
  "Aviation Career Guidance",
  "DGCA Ground Class in dwarka",
  "DGCA Ground Class in delhi"
];

export const SEO_LINK_MAP: Record<string, string> = {
  "CBSE Full Form": "/dgca/full-form",
  "ICSE Full Form": "/dgca/full-form",
  "DGCA Full Form": "/dgca/full-form",
  "PPL Full Form": "/become-a-pilot/become-pilot",
  "CPL Full Form": "/courses/cpl",
  "RTR Full Form": "/rtr",
  "Atpl Full Form": "/air-transport-pilots-license-atpl",
  "Commercial Pilot License": "/courses/cpl",
  "Commercial Pilot License in India": "/courses/cpl",
  "Commercial Pilot License (CPL)": "/courses/cpl",
  "Pilot course": "/pilot-course",
  "Pilot Course": "/pilot-course",
  "Commercial Pilot Course": "/courses/cpl",
  "Best Pilot Training Institute": "/pilot-training",
  "DGCA": "/dgca",
  "CPL": "/courses/cpl",
  "ATPL": "/courses/atpl",
  "PPL": "/become-a-pilot/become-pilot",
  "ATPL Course": "/courses/atpl",
  "CPL Course": "/courses/cpl",
  "Pilot Training": "/pilot-training",
  "Pilot Training in India": "/pilot-training/india",
  "Pilot Training Institute": "/pilot-training",
  "Aviation Academy": "/about",
  "DGCA ground classes": "/dgca/ground-classes",
  "commercial pilot": "/courses/cpl",
  "commercial pilot license salary": "/courses/cpl",
  "Pilot training": "/pilot-training",
  "Commercial Pilot Training": "/courses/cpl",
  "commercial pilot course": "/courses/cpl",
  "commercial pilot licence course": "/courses/cpl",
  "cpl course fees": "/courses/cpl",
  "commercial pilot training": "/courses/cpl",
  "commercial pilot eligibility": "/courses/cpl",
  "commercial pilot training in india": "/courses/cpl",
  "cpl licence cost": "/courses/cpl",
  "commercial pilot license course in india": "/courses/cpl",
  "commercial pilot fees": "/courses/cpl",
  "commercial pilot course eligibility": "/courses/cpl",
  "commercial pilot license syllabus": "/courses/cpl",
  "Commercial Pilot License Admission Process": "/courses/cpl",
  "Become a Pilot": "/how-to-become-a-pilot",
  "how to become a pilot": "/how-to-become-a-pilot",
  "How to Become a Pilot": "/how-to-become-a-pilot",
  "how to become a pilot in india": "/how-to-become-a-pilot-in-india-after-12th",
  "how to become a pilot after 12th": "/how-to-become-a-pilot-after-12th",
  "Private Pilot License": "/become-a-pilot/become-pilot",
  "Private Pilot License (PPL)": "/become-a-pilot/become-pilot",
  "CPL Course": "/courses/cpl",
  "pilot course fees": "/pilot-course",
  "Pilot Course Fees": "/pilot-course",
  "Pilot Salary in India": "/courses/cpl",
  "pilot training fees": "/pilot-training",
  "qualifications to become a pilot": "/how-to-become-a-pilot",
  "best pilot schools": "/pilot-training",
  "eligibility for become a pilot": "/how-to-become-a-pilot",
  "pilot syllabus": "/pilot-training",
  "pilot training eligibility": "/pilot-training",
  "Pilot Eligibility": "/pilot-training",
  "CPL Eligibility": "/courses/cpl",
  "eligibility for pilot course": "/pilot-course",
  "ppl syllabus": "/become-a-pilot/become-pilot",
  "pilot course syllabus": "/pilot-course",
  "ppl pilot salary": "/become-a-pilot/become-pilot",
  "private pilot license syllabus": "/become-a-pilot/become-pilot",
  "Pilot training in India": "/pilot-training/india",
  "Pilot training in Hyderabad": "/locations/hyderabad",
  "Pilot training in Mumbai": "/locations/mumbai",
  "Pilot Training in Chennai": "/locations/chennai",
  "Pilot Training in Bangalore": "/locations/bangalore",
  "Pilot training in kerala": "/locations/kerala",
  "Pilot training in Delhi": "/locations/delhi",
  "Pilot Training in Pune": "/locations/pune",
  "Pilot training institute in Kolkata": "/locations/kolkata",
  "pilot training in coimbatore": "/locations/coimbatore",
  "Pilot training in Gujarat": "/locations/gujarat",
  "Pilot training in goa": "/locations/goa",
  "Pilot Training in Gurgaon": "/locations/gurgaon",
  "Pilot training in tamil nadu": "/locations/tamil-nadu",
  "Pilot Training in Rajasthan": "/locations/rajasthan",
  "Pilot Training in Haryana": "/locations/haryana",
  "Pilot Training in Punjab": "/locations/punjab",
  "Pilot Training in Andhra Pradesh": "/locations/andhra-pradesh",
  "Pilot Training in Arunachal Pradesh": "/locations/arunachal-pradesh",
  "Pilot training in Assam": "/locations/assam",
  "Pilot Training in Bihar": "/locations/bihar",
  "Pilot Training in Chhattisgarh": "/locations/chhattisgarh",
  "Pilot Training in Himachal Pradesh": "/locations/himachal-pradesh",
  "Pilot Training in Noida": "/locations/noida",
  "Pilot Training in Ghaziabad": "/locations/ghaziabad",
  "Pilot Training in Nagpur": "/locations/nagpur",
  "Pilot Training in Maharashtra": "/locations/maharashtra",
  "Pilot Training in Jaipur": "/locations/jaipur",
  "Airline Transport Pilot License": "/air-transport-pilots-license-atpl",
  "airline transport pilot license": "/airline-transport-pilot-licence-atpl",
  "atpl": "/courses/atpl",
  "atpl license": "/courses/atpl",
  "airline transport license": "/air-transport-pilots-license-atpl",
  "atp licence": "/become-a-pilot/airline-transport-pilot-licence",
  "airline transport pilot licence cost": "/courses/atpl",
  "atpl cost": "/courses/atpl",
  "atpl requirements": "/courses/atpl",
  "atpl training": "/courses/atpl",
  "atpl pilot salary": "/courses/atpl",
  "Student Pilot License": "/become-a-pilot/become-pilot",
  "spl": "/become-a-pilot/become-pilot",
  "student pilot license": "/become-a-pilot/become-pilot",
  "student pilot certificate": "/become-a-pilot/become-pilot",
  "student pilot license cost": "/become-a-pilot/become-pilot",
  "spl pilot training fees": "/become-a-pilot/become-pilot",
  "student pilot license requirements": "/become-a-pilot/become-pilot",
  "student pilot license eligibility": "/become-a-pilot/become-pilot",
  "student pilot license fees": "/become-a-pilot/become-pilot",
  "spl eligibility": "/become-a-pilot/become-pilot",
  "spl fees": "/become-a-pilot/become-pilot",
  "Pilot Training Course": "/pilot-training",
  "DGCA Ground Class": "/dgca/ground-classes",
  "DGCA Ground Classes": "/dgca/ground-classes",
  "DGCA Ground School": "/dgca/ground-classes",
  "DGCA Coaching": "/dgca/ground-classes",
  "DGCA Computer Number": "/dgca",
  "DGCA Exams": "/dgca",
  "ground class": "/dgca/ground-classes",
  "dgca pariksha": "/dgca",
  "pariksha dgca": "/dgca",
  "dgca exam": "/dgca",
  "dgca central examination organization": "/dgca",
  "pilot exam": "/dgca",
  "dgca pariksha portal": "/dgca",
  "dgca exam fees": "/dgca",
  "dgca exam for pilot": "/dgca",
  "dgca exam eligibility": "/dgca",
  "dgca pilot exam": "/dgca",
  "what is dgca exam": "/dgca",
  "dgca exam date": "/dgca",
  "dgca cpl exam": "/courses/cpl",
  "dgca exams for cpl": "/courses/cpl",
  "www pariksha dgca": "/dgca",
  "how to apply for dgca exam": "/dgca",
  "dgca exam age limit": "/dgca",
  "dgca exam schedule": "/dgca",
  "dgca pariksha com": "/dgca",
  "aviation exam in india": "/dgca",
  "dgca entrance exam": "/dgca",
  "e pariksha dgca": "/dgca",
  "egca login": "/dgca",
  "egca": "/dgca",
  "egca dgca": "/dgca",
  "dgca login": "/dgca",
  "edgca": "/dgca",
  "ecga": "/dgca",
  "egca full form": "/dgca/full-form",
  "egca registration": "/dgca/full-form",
  "RTR(A)": "/rtr",
  "RTR(A) Classes": "/rtr",
  "Flying School": "/pilot-training/india",
  "Flying Schools": "/pilot-training/india",
  "Flight Training": "/pilot-training",
  "Aviation Career": "/courses/airline-preparation",
  "Airline Pilot Training": "/courses/cpl",
  "Airline Career": "/courses/airline-preparation",
  "Aviation Career Guidance": "/courses/airline-preparation",
  "DGCA Ground Class in dwarka": "/dgca/ground-classes",
  "DGCA Ground Class in delhi": "/dgca/ground-classes"
};

export const KEYWORD_LINKS = GLOBAL_KEYWORDS.map((keyword) => ({
  keyword,
  href: SEO_LINK_MAP[keyword] || "/pilot-training"
}));
