import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * THE RENDER GATE.
 *
 * Production serves a route only if `scripts/prerender.js` wrote a file for it,
 * and that script builds its route list from `src/lib/routeMeta.ts`. A URL in
 * sitemap.xml that is absent from routeMeta.ts is advertised to Google and to
 * every AI crawler and returns HTTP 404.
 *
 * On 2026-09-04 that was true of 15 of the 48 URLs in the sitemap. This test
 * exists so it can never silently be true again: sitemap.xml is the
 * advertisement, routeMeta.ts is the gate, and a URL needs both.
 */
const ROOT = resolve(__dirname, "../..");
const ORIGIN = "https://www.flystar.co.in";

function routeMetaPaths(): Set<string> {
  const file = readFileSync(resolve(ROOT, "src/lib/routeMeta.ts"), "utf8");
  const block = file.match(
    /const routeMeta: Record<string, RouteMeta> = \{([\s\S]*?)\n\};/m
  );
  if (!block) throw new Error("Could not parse routeMeta — the prerender script parses it the same way, so it is broken too.");
  const paths = new Set<string>(["/"]);
  for (const line of block[1].split("\n")) {
    const m = line.trim().match(/^"([^"]+)":\s*\{/);
    if (m) paths.add(m[1]);
  }
  return paths;
}

/**
 * Imported rather than regex-scraped, because posts now come from two places:
 * the ones committed in blogData.js and the ones scripts/fetch-blogs.mjs pulls
 * from /api/blogs into blogData.remote.js at build time. getBlogRoutes() is what
 * scripts/prerender.js itself calls, so this asks the exact same question the
 * build does.
 */
async function blogPaths(): Promise<string[]> {
  const mod = await import("../lib/blogData.js");
  return mod.getBlogRoutes();
}

function sitemapPaths(): string[] {
  const xml = readFileSync(resolve(ROOT, "public/sitemap.xml"), "utf8");
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)]
    .map((m) => m[1].replace(ORIGIN, ""))
    .map((p) => (p === "" ? "/" : p));
}

function vercelRedirectSources(): Set<string> {
  const config = JSON.parse(readFileSync(resolve(ROOT, "vercel.json"), "utf8"));
  const routes = Array.isArray(config.routes) ? config.routes : [];
  return new Set(
    routes
      .filter((r) => r && typeof r.src === "string" && r.status && r.status >= 300 && r.status < 400)
      .map((r) => r.src)
  );
}

describe("render gate", () => {
  it("prerenders the reference pages and keeps the feed generated", async () => {
    const rendered = new Set([...routeMetaPaths(), ...(await blogPaths())]);
    for (const p of ["/faq", "/glossary", "/editorial-policy"]) {
      expect(rendered.has(p), `${p} must be in routeMeta or it 404s in production`).toBe(true);
    }
    const feed = readFileSync(resolve(ROOT, "public/feed.xml"), "utf8");
    expect(
      feed.includes("GENERATED by scripts/generate-feed.mjs"),
      "feed.xml lost its generated header — run `npm run feed` instead of editing it"
    ).toBe(true);
  });

  it("advertises every topic hub, and every hub is in the render gate", async () => {
    const { TOPICS } = await import("../lib/blogTopics");
    const advertised = new Set(sitemapPaths());
    const gated = new Set(routeMetaPaths());
    for (const t of TOPICS) {
      const path = `/blog/topic/${t.slug}`;
      expect(gated.has(path), `${path} missing from routeMeta — it would 404 in production`).toBe(true);
      expect(advertised.has(path), `${path} missing from sitemap.xml`).toBe(true);
    }
  });

  it("keeps every advertised blog post in the feed", async () => {
    const mod = await import("../lib/blogData.js");
    const feed = readFileSync(resolve(ROOT, "public/feed.xml"), "utf8");
    // Topic hubs live under /blog/topic/ and are not articles: they carry no
    // date, no author and no body of their own, so an RSS reader has nothing to
    // do with them. Only posts belong in the feed.
    const advertised = sitemapPaths().filter((p) => p.startsWith("/blog/") && !p.startsWith("/blog/topic/"));
    const missing = advertised.filter((p) => !feed.includes(`${ORIGIN}${p}<`));
    expect(missing, `in the sitemap but not the feed: ${missing.join(", ")}`).toEqual([]);
    expect(mod.BLOG_POSTS.length).toBeGreaterThan(0);
  });

  it("keeps sitemap.xml generated, never hand-edited", () => {
    const xml = readFileSync(resolve(ROOT, "public/sitemap.xml"), "utf8");
    expect(
      xml.includes("GENERATED by scripts/generate-sitemap.mjs"),
      "sitemap.xml lost its generated header — run `npm run sitemap` instead of editing it by hand"
    ).toBe(true);
  });

  it("prerenders every URL the sitemap advertises", async () => {
    const rendered = new Set([...routeMetaPaths(), ...(await blogPaths())]);
    const dead = sitemapPaths().filter((p) => !rendered.has(p));
    expect(dead, `sitemap.xml advertises URLs that prerender never writes, so they 404: ${dead.join(", ")}`).toEqual([]);
  });

  it("does not advertise a URL that only exists as a redirect", () => {
    const redirects = vercelRedirectSources();
    const advertised = sitemapPaths().filter((p) => redirects.has(p));
    expect(advertised, `sitemap.xml should list destinations, not redirect sources: ${advertised.join(", ")}`).toEqual([]);
  });

  it("permanently redirects duplicate keyword URLs to their primary pages", () => {
    const config = JSON.parse(readFileSync(resolve(ROOT, "vercel.json"), "utf8"));
    const redirects = new Map(
      config.routes
        .filter((r: { src?: string; dest?: string; status?: number }) => r.status === 308)
        .map((r: { src: string; dest: string }) => [r.src, r.dest]),
    );
    const expected = {
      "/best-cpl-ground-classes": "/courses/cpl",
      "/commercial-pilot-training": "/courses/cpl",
      "/commercial-pilot-training-in-dwarka": "/courses/cpl",
      "/courses-and-careers": "/courses/cpl",
      "/commercial-pilot-training-cpl": "/courses/cpl",
      "/best-atpl-classes-in-india": "/courses/atpl",
      "/air-transport-pilots-license-atpl": "/courses/atpl",
      "/cpl-atpl-ground-classes-2": "/dgca/ground-classes",
      "/dgca-ground-classes-training-classes": "/dgca/ground-classes",
      "/how-to-become-a-pilot": "/become-a-pilot/become-pilot",
      "/how-to-become-a-pilot-in-india": "/become-a-pilot/become-pilot",
      "/training-in-india": "/pilot-training/india",
    };
    for (const [source, destination] of Object.entries(expected)) {
      expect(redirects.get(source), `${source} must redirect permanently`).toBe(destination);
    }
  });

  it("keeps every canonical inside routeMeta pointing at its own path", () => {
    const file = readFileSync(resolve(ROOT, "src/lib/routeMeta.ts"), "utf8");
    const entries = [...file.matchAll(/"(\/[^"]*)":\s*\{[^}]*?canonical:\s*`\$\{BASE_URL\}([^`]*)`/g)];
    expect(entries.length).toBeGreaterThan(30);
    const mismatched = entries
      .filter(([, path, canonical]) => path !== canonical && `${path}/` !== canonical)
      .map(([, path, canonical]) => `${path} → ${canonical}`);
    // Every route in routeMeta is a primary page; aliases are edge redirects
    // and therefore do not belong in this metadata map.
    expect(mismatched).toEqual([]);
  });

  it("canonicalizes keyword aliases to their real page address", async () => {
    const { getRouteMeta } = await import("../lib/routeMeta.ts");
    const aliases = {
      "/contact-us": "/contact",
      "/best-atpl-classes-in-india": "/courses/atpl",
      "/commercial-pilot-training": "/courses/cpl",
      "/pilot-course": "/courses/airline-preparation",
      "/how-to-become-a-pilot": "/become-a-pilot/become-pilot",
      "/training-in-india": "/pilot-training/india",
    };

    for (const [alias, canonical] of Object.entries(aliases)) {
      expect(getRouteMeta(alias)?.canonical).toBe(`https://www.flystar.co.in${canonical}`);
      expect(getRouteMeta(alias)?.ogUrl).toBe(`https://www.flystar.co.in${canonical}`);
    }
  });
});
