/**
 * Build-time blog fetch.
 *
 * Posts written through /admin/blog live in MongoDB and are served by
 * /api/blogs. Until this script existed, `scripts/prerender.js` only knew about
 * the posts hardcoded in `src/lib/blogData.js`, so an admin-published post got
 * no static file, no meta tags and no sitemap entry — visible to a human via the
 * runtime fetch in BlogDetail.tsx, invisible to Google and every AI crawler.
 *
 * This runs BEFORE `vite build` (see the `prebuild` script). It writes
 * `src/lib/blogData.remote.js`, which `blogData.js` merges into BLOG_POSTS, so
 * routeMeta, the schema builder, the prerender route list and the generated
 * sitemap all see one set of posts.
 *
 * FAILS SOFT. If the API is unreachable — Render cold start, deploy-time
 * outage, no network — the previously generated file is left in place and the
 * build continues with whatever it already had. A blog outage must never break
 * a deploy of the whole site.
 *
 * Every post passes a quality gate before it is allowed into the sitemap; see
 * `blog-gate.json`. The gate exists because the database already contained a
 * post with an SEO-spam block in it.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { partition } from "./blogGate.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "src/lib/blogData.remote.js");
const REPORT = path.join(ROOT, "blog-gate-report.json");
const GATE = path.join(ROOT, "blog-gate.json");

const API =
  process.env.BLOG_API_URL ||
  process.env.VITE_API_URL ||
  "https://fly-star-aviation-private-limited.onrender.com";
const TIMEOUT_MS = Number(process.env.BLOG_FETCH_TIMEOUT_MS || 45000);

const gate = JSON.parse(fs.readFileSync(GATE, "utf8"));

async function main() {
  let posts;
  try {
    const res = await fetch(`${API}/api/blogs`, {
      signal: AbortSignal.timeout(TIMEOUT_MS),
      headers: { accept: "application/json" },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    posts = await res.json();
    if (!Array.isArray(posts)) throw new Error("response was not an array");
  } catch (err) {
    console.warn(`[fetch-blogs] API unreachable (${err.message}).`);
    if (fs.existsSync(OUT)) {
      console.warn("[fetch-blogs] Keeping the previously generated blogData.remote.js.");
    } else {
      fs.writeFileSync(OUT, emit([], "API unreachable and no previous file existed"));
      console.warn("[fetch-blogs] Wrote an empty remote set. Static posts still build.");
    }
    return;
  }

  const { accepted, rejected } = partition(posts, gate);

  fs.writeFileSync(OUT, emit(accepted, `fetched ${posts.length}, accepted ${accepted.length}`));
  fs.writeFileSync(
    REPORT,
    JSON.stringify({ fetchedAt: new Date().toISOString(), api: API, total: posts.length, accepted: accepted.map((p) => p.slug), rejected }, null, 2) + "\n"
  );

  console.log(`[fetch-blogs] ${posts.length} fetched, ${accepted.length} accepted, ${rejected.length} held back.`);
  for (const r of rejected) console.log(`[fetch-blogs]   held back: ${r.slug || r.id} — ${r.reason}`);
}

function emit(posts, note) {
  return `// GENERATED by scripts/fetch-blogs.mjs — do not edit by hand.
// ${note}
// Generated ${new Date().toISOString()}
export const REMOTE_BLOG_POSTS = ${JSON.stringify(posts, null, 2)};
`;
}

main();
