/**
 * Generate public/feed.xml (RSS 2.0) from the same post list everything else
 * reads.
 *
 * Why a feed still matters: aggregators and several answer engines discover new
 * content through feeds rather than waiting for a crawl, and a feed is the
 * cheapest freshness signal a site can emit. This one costs nothing to maintain
 * because it is generated, not written.
 *
 * Runs in `prebuild`, beside the sitemap, from src/lib/blogData.js — so a post
 * added to the static list or approved from the database appears here with no
 * further action.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ORIGIN = "https://www.flystar.co.in";
const OUT = path.join(ROOT, "public/feed.xml");

/** Same threshold the sitemap uses — a feed should not advertise a stub. */
const MIN_WORDS = 300;
const MAX_ITEMS = 30;

function esc(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Post dates are ISO ("2026-09-04") or already RFC-ish. Feeds want RFC 822. */
function rfc822(value) {
  const d = value ? new Date(value) : new Date();
  return (Number.isNaN(d.getTime()) ? new Date() : d).toUTCString();
}

async function main() {
  const mod = await import(path.join(ROOT, "src/lib/blogData.js"));

  const items = mod.BLOG_POSTS.filter((p) => p.slug && mod.getWordCount(p) >= MIN_WORDS)
    .sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0))
    .slice(0, MAX_ITEMS);

  const body = items
    .map((post) => {
      const url = `${ORIGIN}/blog/${post.slug}`;
      const description = post.metaDescription || post.excerpt || "";
      const categories = (post.tags || []).map((t) => `      <category>${esc(t)}</category>`).join("\n");
      return [
        "    <item>",
        `      <title>${esc(post.seoTitle || post.title)}</title>`,
        `      <link>${url}</link>`,
        `      <guid isPermaLink="true">${url}</guid>`,
        `      <pubDate>${rfc822(post.createdAt)}</pubDate>`,
        `      <description>${esc(description)}</description>`,
        post.author ? `      <dc:creator>${esc(post.author)}</dc:creator>` : "",
        categories,
        "    </item>",
      ]
        .filter(Boolean)
        .join("\n");
    })
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/generate-feed.mjs from src/lib/blogData.js. Do not edit by hand. -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Flying Star Aviator — DGCA and pilot training guides</title>
    <link>${ORIGIN}/blogs</link>
    <atom:link href="${ORIGIN}/feed.xml" rel="self" type="application/rss+xml" />
    <description>Sourced guides to DGCA examinations, licences and pilot training in India, from Flying Star Aviator, Dwarka, New Delhi.</description>
    <language>en-in</language>
    <lastBuildDate>${rfc822(items[0]?.createdAt)}</lastBuildDate>
${body}
  </channel>
</rss>
`;

  fs.writeFileSync(OUT, xml);
  console.log(`[feed] ${items.length} items written to public/feed.xml`);
}

main();
