/**
 * Generate public/sitemap.xml from the render gate itself.
 *
 * The bug this removes: sitemap.xml was maintained by hand while prerendering
 * was driven by src/lib/routeMeta.ts. The two drifted, and on 2026-09-04 fifteen
 * of the forty-eight advertised URLs returned HTTP 404 to Google and to every AI
 * crawler. src/test/renderGate.test.ts catches that drift; generating the file
 * from the same source makes the drift impossible in the first place.
 *
 * Runs before `vite build` so Vite copies the result out of public/.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ORIGIN = "https://www.flystar.co.in";
const OUT = path.join(ROOT, "public/sitemap.xml");

/** Routes that render but must never be advertised. */
const EXCLUDE = new Set(["/admin/login", "/sitemap", "/Sitemap"]);
const EXCLUDE_PREFIX = ["/admin", "/assets/"];

function routeMetaEntries() {
  const file = fs.readFileSync(path.join(ROOT, "src/lib/routeMeta.ts"), "utf8");
  const block = file.match(/const routeMeta: Record<string, RouteMeta> = \{([\s\S]*?)\n\};/m);
  if (!block) throw new Error("Could not parse routeMeta.ts — prerender parses it the same way, so it is broken too.");

  const out = [];
  for (const line of block[1].split("\n")) {
    const m = line.trim().match(/^"([^"]+)":\s*\{/);
    if (m) out.push(m[1]);
  }
  return out;
}

/**
 * An alias route renders the same component as a canonical one and exists only
 * to keep a legacy URL alive. Advertising both would offer search engines two
 * URLs for one page, so only the canonical goes in the sitemap.
 */
function aliasPaths() {
  const file = fs.readFileSync(path.join(ROOT, "src/lib/routes.ts"), "utf8");
  const block = file.match(/ALIAS_CANONICAL: Record<string, string> = \{([\s\S]*?)\n\};/m);
  if (!block) return new Set();
  return new Set([...block[1].matchAll(/"([^"]+)":\s*"[^"]+"/g)].map((m) => m[1]));
}

/**
 * Only canonical, substantive posts are advertised.
 *
 * getBlogRoutes() also returns legacy /blogs/<id> URLs for posts that have no
 * slug — which includes the four title-only stubs (_id 3-6) that carry no body
 * text. Those still prerender, and they still resolve for anyone holding an old
 * link, but putting them in the sitemap would be actively asking Google to index
 * empty pages. A sitemap is a recommendation, not an inventory.
 */
const MIN_SITEMAP_WORDS = 300;

async function blogPaths() {
  const mod = await import(path.join(ROOT, "src/lib/blogData.js"));
  const skipped = [];
  const paths = [];

  for (const post of mod.BLOG_POSTS) {
    if (!post.slug) {
      skipped.push(`${post._id} (no slug — legacy /blogs/<id> only)`);
      continue;
    }
    const words = mod.getWordCount(post);
    if (words < MIN_SITEMAP_WORDS) {
      skipped.push(`${post.slug} (${words} words)`);
      continue;
    }
    paths.push(`/blog/${post.slug}`);
  }

  for (const s of skipped) console.log(`[sitemap] blog post not advertised: ${s}`);
  return paths;
}

function isoToday() {
  return new Date().toISOString().slice(0, 10);
}

/** Keep the existing lastmod for URLs whose entry has not changed. */
function previousLastmod() {
  if (!fs.existsSync(OUT)) return new Map();
  const xml = fs.readFileSync(OUT, "utf8");
  return new Map(
    [...xml.matchAll(/<loc>([^<]+)<\/loc><lastmod>([^<]+)<\/lastmod>/g)].map((m) => [
      m[1].replace(ORIGIN, "") || "/",
      m[2],
    ])
  );
}

async function main() {
  const aliases = aliasPaths();
  const previous = previousLastmod();
  const today = isoToday();

  const paths = new Set(["/"]);
  for (const p of routeMetaEntries()) {
    const clean = p !== "/" && p.endsWith("/") ? p.slice(0, -1) : p;
    if (EXCLUDE.has(clean)) continue;
    if (EXCLUDE_PREFIX.some((pre) => clean.startsWith(pre))) continue;
    if (aliases.has(clean)) continue;
    paths.add(clean);
  }
  for (const p of await blogPaths()) paths.add(p);

  const sorted = [...paths].sort((a, b) => (a === "/" ? -1 : b === "/" ? 1 : a.localeCompare(b)));

  const body = sorted
    .map((p) => {
      const loc = p === "/" ? `${ORIGIN}/` : `${ORIGIN}${p}`;
      const lastmod = previous.get(p) || today;
      return `  <url><loc>${loc}</loc><lastmod>${lastmod}</lastmod></url>`;
    })
    .join("\n");

  fs.writeFileSync(
    OUT,
    `<?xml version="1.0" encoding="UTF-8"?>\n<!-- GENERATED by scripts/generate-sitemap.mjs from src/lib/routeMeta.ts + blogData. Do not edit by hand. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`
  );
  console.log(`[sitemap] ${sorted.length} URLs written, all of them prerendered.`);
}

main();
